### ISSUE TITLE
 impossible to configure

### ISSUE THREAD

**Issue by Bksp** [DoggyCraft/MyDog#35]
I configure the yml file and when reloading it does not save and rewrite the configurations

**Comment by HeroGamers** [comment]
What version of MyDog are you running, and version of Spigot/Paper?
Can you provide some logs?

Will try to reproduce.

**Comment by Bksp** [comment]
3405-Spigot-f4ff00f-d10c35e (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)


### > [00:04:28] [Server thread/INFO]: [MyDog] Loading MyDog v0.1.3
> [00:04:28] [Server thread/INFO]: [BetterTridents] Loading BetterTridents v2.2.1
> [00:04:28] [Server thread/INFO]: [ArmedArmorStands] Loading ArmedArmorStands v1.2.3
> [00:04:28] [Server thread/INFO]: [CombatWeaponryPlus] Loading CombatWeaponryPlus v1.4.7
> [00:04:28] [Server thread/INFO]: [Replenish] Loading Replenish v1.4
> [00:04:28] [Server thread/INFO]: [AuthMe] Loading AuthMe v5.6.0-beta2-b2453
> [00:04:28] [Server thread/INFO]: [GrapplingHook] Loading GrapplingHook v1.6.2
> [00:04:28] [Server thread/INFO]: [ShulkerRespawn] Loading ShulkerRespawn v1.1
> [00:04:28] [Server thread/INFO]: [Geyser-Spigot] Loading Geyser-Spigot v2.0.0-SNAPSHOT
> [00:04:28] [Server thread/INFO]: [ClickTpa] Loading ClickTpa v1.5.1
> [00:04:28] [Server thread/INFO]: [LaggRemover] Loading LaggRemover v2.0.6
> [00:04:28] [Server thread/INFO]: [ChestSort] Loading ChestSort v12.1.4
> [00:04:28] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.3.30
> [00:04:29] [Server thread/INFO]: __
> [00:04:29] [Server thread/INFO]: | |__) LuckPerms v5.3.30
> [00:04:29] [Server thread/INFO]: |___ | Running on Bukkit - CraftBukkit
> [00:04:29] [Server thread/INFO]:
> [00:04:29] [Server thread/INFO]: [LuckPerms] Loading configuration...
> [00:04:29] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
> [00:04:29] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
> [00:04:30] [Server thread/INFO]: [LuckPerms] Performing initial data load...
> [00:04:30] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 1603ms)
> [00:04:30] [Server thread/INFO]: [MyDog] Enabling MyDog v0.1.3
> [00:04:30] [Server thread/INFO]: [MyDog] Vault not found.
> [00:04:30] [Server thread/INFO]: [MyDog] Loaded 1 dogs.

**Comment by HeroGamers** [comment]
What configurations are you configuring?

**Comment by Bksp** [comment]
anyone

**Comment by HeroGamers** [comment]
I've just tried changing some configurations, and they seem to get saved correctly..?
They are not being overwritten on restart either.

Do you edit the file manually, and then follow the change with `/mydog reload`? It should load the new configurations, and save them.

**Comment by Bksp** [comment]
SOLVED MY BAD SO SORRY

**Comment by HeroGamers** [comment]
Mind if I ask what the issue was, or what caused the issue?
Seems some other people have had the same problems in the past, so mind if I asked how you expected it to work?
