### ISSUE TITLE
Dogs not gaining HP or doing more damage

### ISSUE THREAD

**Issue by SinistersGrin** [DoggyCraft/MyDog#63]
Despite the level of the dog 1-10 Damage = 4.0 HP and Health = 21
could it be Mcmmo causing an issue?
![image](https://user-images.githubusercontent.com/115602637/201608900-c303a705-12cd-49eb-9310-6a1ed50f4499.png)

**Comment by HeroGamers** [comment]
Hi there,
If a dog levels up while playing, can you check if the damage and health changes? And do you have any settings in the config set to have the health be 21?
I don't think the default Wolf health is 21, so yeah, it's likely that something could be interfering, but I can't say for sure with the current information.

You can try to enable `debug` in the configuration and send some logs for when a dog levels up, it should say something along the lines of "old health" and "new health".

**Comment by SinistersGrin** [comment]
Yeah Default health is not 21, it was Mcmmo and i don't know what they did to fix it on their end but i was sent a jar from them and its all working fine now, and we are loving it!
I do have another more private question so i feel like it would be better on discord, thats completely your choice if you'd want to take the time, but thank you for your time here!
Sinisters Grin#4934

**Comment by HeroGamers** [comment]
Oh, so I guess they fixed it - nice!

If you are in the SpigotMC Discord Server you can DM me.

HeroGamers#0900 (Spigot Username / Server Nickname: fido2603)
