### ISSUE TITLE
Disappearing Dog

### ISSUE THREAD

**Issue by bizkid1** [DoggyCraft/MyDog#64]
I originally had three dogs - one died (#2).  I rode on a horse away from "home" with the remaining two dogs (#1 and #3) and when I arrived at where I was going, one of the two dogs was nowhere to be found (#1).  It showed in my inventory but /md comehere did not surface a dog.  I back tracked my path but still could not locate the dog.  I ended up running /md free to get it out of my inventory but no clue where the dog went.

**Comment by HeroGamers** [comment]
Hi there, thanks for opening an issue!
I don't have much information to go on though - the dogs try and teleport to you, and their locations get updated every time they are interacted with and when they get teleported. This location gets saved by MyDog, and can be viewed by running `/md info`.
Of course, the dog might not be where the plugin says it last saw the dog, but I don't know what else to do right now, seeing as I don't have enough information to try and reproduce the bug myself.

If you figure out a way to reproduce the issue, feel free to reopen the issue!
